apiVersion: batch/v1
kind: CronJob
metadata:
  name: maya-sawa-sync
  labels:
    app.kubernetes.io/name: maya-sawa-sync
spec:
  schedule: "0 3 */3 * *"  # 每3天的凌晨3點執行
  concurrencyPolicy: Forbid  # 防止重複執行
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3  # 移動到正確位置
      template:
        spec:
          serviceAccountName: jenkins-admin
          containers:
          - name: sync-articles
            image: papakao/maya-sawa:latest
            command: ["python", "-c"]
            args:
            - |
              import asyncio
              import sys
              import os
              sys.path.append('.')
              from maya_sawa.api.qa import sync_articles_from_api, SyncFromAPIRequest
              
              async def main():
                  try:
                      request = SyncFromAPIRequest()
                      result = await sync_articles_from_api(request)
                      print(f"同步完成: {result.get('message', '同步完成')}")
                      return 0
                  except Exception as e:
                      print(f"同步失敗: {str(e)}")
                      return 1
              
              if __name__ == "__main__":
                  exit_code = asyncio.run(main())
                  sys.exit(exit_code)
            env:
            - name: OPENAI_API_KEY
              value: "${OPENAI_API_KEY}"
            - name: OPENAI_ORGANIZATION
              value: "${OPENAI_ORGANIZATION}"
            - name: OPENAI_API_BASE
              value: "https://api.openai.com/v1"
            - name: DB_HOST
              value: "${DB_HOST}"
            - name: DB_PORT
              value: "${DB_PORT}"
            - name: DB_DATABASE
              value: "${DB_DATABASE}"
            - name: DB_USERNAME
              value: "${DB_USERNAME}"
            - name: DB_PASSWORD
              value: "${DB_PASSWORD}"
            - name: DB_SSLMODE
              value: "require"
            - name: REDIS_HOST
              value: "${REDIS_HOST}"
            - name: REDIS_CUSTOM_PORT
              value: "${REDIS_CUSTOM_PORT}"
            - name: REDIS_PASSWORD
              value: "${REDIS_PASSWORD}"
            - name: REDIS_QUEUE_MAYA
              value: "${REDIS_QUEUE_MAYA}"
            - name: PUBLIC_API_BASE_URL
              value: "${PUBLIC_API_BASE_URL}"
            - name: PYTHONPATH
              value: "."
            resources:
              requests:
                memory: "256Mi"
                cpu: "100m"
              limits:
                memory: "512Mi"
                cpu: "200m"
          restartPolicy: OnFailure 